---
- name: dnsmasq package
  package:
      state: present
      name:
          - dnsmasq
- name: dnsmasq configuration file for TFTP
  template:
      src: dnsmasq.tftp.j2
      dest: "/etc/dnsmasq.d/tftp.conf"
      trim_blocks: true
  when: tftp is defined
  register: tftp
- name: TFTP server root
  file:
      state: directory
      path: "{{ tftp.root_directory }}"
- name: dnsmasq configuration file for DHCP
  template:
      src: dnsmasq.dhcp.j2
      dest: "/etc/dnsmasq.d/dhcp.conf"
      trim_blocks: true
  when: dhcp is defined
  register: dhcp
- name: Copy bootloader files to TFTP root
  copy:
      src: "{{ item.bootfile }}"
      dest: "{{ tftp.root_directory }}/{{ item.bootfile }}"
  when: item.bootfile is defined and tftp.root_directory is defined
  with_items:
      - "{{ dhcp.hosts | default([]) }}"
- include: handlers/main.yml
